let level1;

function initLevel(){
    level1 = new Level([
            new ChickenNormal(700),
            new ChickenNormal(1000),
            new ChickenNormal(1500),
            new ChickenNormal(1800),
            new ChickenNormal(2500),
            new ChickenNormal(3000),
            new ChickenSmall(900),
            new ChickenSmall(1200),
            new ChickenSmall(1700),
            new ChickenSmall(2100),
            new ChickenSmall(2900),
            new ChickenSmall(3300),
            
            new Endboss(),
        ],
        [
            new Cloud(1, -100),
            new Cloud(2, 400),
            new Cloud(1, 900),
            new Cloud(2, 1400),
            new Cloud(1, 1900),
            new Cloud(2, 2400),
            new Cloud(1, 2900),
            new Cloud(2, 3400),
            new Cloud(1, 3900),
            new Cloud(2, 4400),
            new Cloud(1, 4900),
            new Cloud(2, 5400),
            new Cloud(1, 5900),
            new Cloud(2, 6400),
        ],

        [
            new Coin(500, 500),
            new Coin(1200, 500),
            new Coin(1900, 500),
            new Coin(2600, 500),
            new Coin(3300, 500),
        ],
        [
            new CollectableBottle(300, 200),
            new CollectableBottle(600, 200),
            new CollectableBottle(900, 200),
            new CollectableBottle(1200, 200),
            new CollectableBottle(1500, 200),
            new CollectableBottle(2000, 200),
            new CollectableBottle(2300, 200),
            new CollectableBottle(2700, 200),
            new CollectableBottle(2900, 200),
            new CollectableBottle(3200, 200),
        ],
        [
            new BackgroundObject('img/5_background/layers/air.png', -720 * 2),
            new BackgroundObject('img/5_background/layers/air.png', -720),
            new BackgroundObject('img/5_background/layers/air.png', 0),
            new BackgroundObject('img/5_background/layers/air.png', 720),
            new BackgroundObject('img/5_background/layers/air.png', 720 * 2),
            new BackgroundObject('img/5_background/layers/air.png', 720 * 3),
            new BackgroundObject('img/5_background/layers/air.png', 720 * 4),
            new BackgroundObject('img/5_background/layers/air.png', 720 * 5),
            new BackgroundObject('img/5_background/layers/air.png', 720 * 6),

            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', -720 *2, 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -720 , 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0, 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720, 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720 * 2, 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720 * 3, 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720 * 4, 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 720 * 5, 3),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 720 * 6, 3),

            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', -720 * 2, 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -720, 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0, 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720, 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720 * 2, 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720 * 3, 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720 * 4, 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 720 * 5, 2),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 720 * 6, 2),

            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', -720 * 2),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -720),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),   
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 720 * 2),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720 * 3),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 720 * 4),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 720 * 5),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 720 * 6),

        ],
        level_start_x = -200,
        level_end_x = 4400);    
}
